#!/bin/bash -e

reset

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR=$(dirname $BUILDER_DIR)

function detect_version()
{
    ver=$(awk '/public const string Version = /{ print $6 }' < ${ROOT_DIR}/NervaOneWalletMiner/Helpers/GlobalData.cs)
    export APP_VERSION=$(echo ${ver} | tr -d '";')
    echo App version detected as ${APP_VERSION}: ${APP_CODENAME}
}

function publish()
{
    cd ${ROOT_DIR}
    echo Building $1
    dotnet restore ${ROOT_DIR}/NervaOneWalletMiner.Desktop/NervaOneWalletMiner.Desktop.csproj -r $1

    targetFramework=net8.0

    dotnet publish ${ROOT_DIR}/NervaOneWalletMiner.Desktop/NervaOneWalletMiner.Desktop.csproj -c release -r $1 -f ${targetFramework} -p:publishsinglefile=true

    if [ "$1" == "osx-x64" ] || [ "$1" == "osx-arm64" ]; then
        bundle=${ROOT_DIR}/NervaOneWalletMiner.Desktop/bin/NervaOneDesktop.app
        mkdir -p ${bundle}/Contents
        mkdir -p ${bundle}/Contents/MacOS
        mkdir -p ${bundle}/Contents/Resources

        # Generate plist
        plist=$(sed -e "s/{APP_VERSION}/${APP_VERSION}/" -e "s/{DISPLAY_NAME}/NervaOne/" ${BUILDER_DIR}/Info.plist.template)
        echo "$plist" > ${bundle}/Contents/Info.plist

        # Copy icons to resources
        cp ${BUILDER_DIR}/logos/nerva-logo-color.icns ${bundle}/Contents/Resources/nerva-logo-color.icns
        cp ${BUILDER_DIR}/logos/nerva-logo-color-2.icns ${bundle}/Contents/Resources/nerva-logo-color-2.icns

        # Copy launcher
        cp -R ${ROOT_DIR}/NervaOneWalletMiner.Desktop/bin/release/${targetFramework}/$1/publish/* ${bundle}/Contents/MacOS/

        cd ${ROOT_DIR}/NervaOneWalletMiner.Desktop/bin
        zip -r ${ROOT_DIR}/NervaOneWalletMiner.Desktop/bin/nervaone-desktop-v${APP_VERSION}_$1.zip ./NervaOneDesktop.app
    elif [ "$1" == "linux-x64" ] || [ "$1" == "linux-arm64" ]; then
        bundle=${ROOT_DIR}/NervaOneWalletMiner.Desktop/bin/NervaOneDesktop
        mkdir -p ${bundle}/Contents
        mkdir -p ${bundle}/Resources

        cp ${BUILDER_DIR}/logos/nerva-logo-color.png ${bundle}/Resources/nerva-logo-color.png
        cp ${BUILDER_DIR}/logos/nerva-logo-color-2.png ${bundle}/Resources/nerva-logo-color-2.png

        cp ${ROOT_DIR}/NervaOneWalletMiner.Desktop/bin/release/${targetFramework}/$1/publish/* ${bundle}/Contents/
        cp ${BUILDER_DIR}/install ${bundle}/install
        chmod +x ${bundle}/install

        cd ${ROOT_DIR}/NervaOneWalletMiner.Desktop/bin
        zip -r ${ROOT_DIR}/NervaOneWalletMiner.Desktop/bin/nervaone-desktop-v${APP_VERSION}_$1.zip ./NervaOneDesktop
    # else
        # cd ${ROOT_DIR}/NervaOneWalletMiner.Desktop/bin
        # zip -j ${ROOT_DIR}/NervaOneWalletMiner.Desktop/bin/nervaone-desktop-v${APP_VERSION}_$1.zip ./release/${targetFramework}/$1/publish/*
    fi
}

detect_version

publish $1