#!/bin/bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

bd=~/Downloads/NervaOneDesktop

dd=~/.local/share/applications/nervaone.desktop


echo "Creating launcher"
echo "[Desktop Entry]" > ${dd}
echo "Type=Application" >> ${dd}
echo "Name=NervaOne" >> ${dd}
echo "Comment=NervaOne Desktop" >> ${dd}
echo "Exec=${bd}/Contents/NervaOneDesktop" >> ${dd}
echo "Icon=${bd}/Resources/nerva-logo-color.png" >> ${dd}
echo "Terminal=false" >> ${dd}

chmod +x ${dd}

echo "Finished"