#!/bin/bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

dd=~/.local/share/applications/nervaone.desktop


echo "Creating launcher"
echo "[Desktop Entry]" > ${dd}
echo "Type=Application" >> ${dd}
echo "Name=NervaOne" >> ${dd}
echo "Comment=NervaOne Desktop" >> ${dd}
echo "Exec=${dir}/Contents/NervaOneDesktop" >> ${dd}
echo "Icon=${dir}/Resources/nerva-logo-color.png" >> ${dd}
echo "Terminal=false" >> ${dd}

chmod +x ${dd}

echo "Installer finished successfully. You can now open NervaOne from your Applications."