#!/bin/bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

mkdir -p ~/.local/bin/nervaone
mkdir -p ~/.local/share/applications

bd=$(~/.local)

dd=${bd}/share/applications/nervaone.desktop

echo "Copying files to ~/.local/bin/nervaone/"
cp ${dir}/Contents/* ~/.local/bin/nervaone/
cp ${dir}/Resources/nerva-logo-color.png ~/.local/bin/nervaone/nerva-logo-color.png

echo "Creating launcher"
echo "[Desktop Entry]" > ${dd}
echo "Name=NervaOne Desktop" >> ${dd}
echo "Exec=${bd}/bin/nervaone/NervaOneWalletMiner.Desktop" >> ${dd}
echo "Icon=${bd}/bin/nervaone/nerva-logo-color.png" >> ${dd}
echo "Terminal=false" >> ${dd}
echo "Type=Application" >> ${dd}

chmod +x ${dd}

echo "Finished"